### ISSUE TITLE
update hyperLOPIT data

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#11]
Add line of code to convert missing localisations to 'unknown' or 'unlabelled' see `fDataToUnknown`

**Comment by lmsimp** [comment]
@lgatto now done and re-ordered fractions. The only thing is now we have re-ordered fractions PCA looks different  i.e. y-axis is now mirrored. Of course, this does not change anything except annoying for us and people familiar with data. Now sure if we should change back?

**Comment by lgatto** [comment]
Yes, that's a bit annoying. May be better to revert the order, but use `o<-order(hyperLOPIT2015$fractions)` and `plotDist(hyperLOPIT2015[, o])` when we plot profiles.

**Comment by lmsimp** [comment]
Agreed, have reverted

**Comment by lmsimp** [comment]
Fix `pData` and add fraction numbers

**Comment by lmsimp** [comment]
Can you check `pData` and see if this is okay? Thank you.

**Comment by lgatto** [comment]
Yes, looks good.
