### ISSUE TITLE
validObject(E14TG2aS1goCC) 

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#12]
FALSE

**Comment by lmsimp** [comment]
Fixed in https://github.com/lgatto/pRolocdata/commit/41a8fbd088b1a0a99075d7b1f259442127e3ed54

**Comment by lgatto** [comment]
@lmsimp did you check the other CC objects?

**Comment by lmsimp** [comment]
As are a I remember, yes. I will double check.

**Comment by lgatto** [comment]
TODO: unit tests for data validity

**Comment by lgatto** [comment]
@lmsimp I have created the unit tests - `E14TG2aS1goCC` is not valid.

**Comment by lgatto** [comment]
@lmsimp - we must not forget this

**Comment by lgatto** [comment]
It seems that all objects are actually valid now. Closing.
