### ISSUE TITLE
params used in TL

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#13]
- Add params to this issue
- OR add to `MSnSet` instance in `pRolocdata`
- OR create file in `inst/extdata` to record all params

**Comment by lgatto** [comment]
I think a text/md file in `inst/extdata` would be best, as it is easy to update/annotate. I would discourage the github issue solution, as these are not backup elsewhere (we could, though).

**Comment by lmsimp** [comment]
This was already [here](https://github.com/lgatto/pRolocdata/tree/master/inst/extdata/tl-res)

**Comment by lmsimp** [comment]
I would prefer to add these to the objects though. Maybe not a high priority right now as they are already in the package

**Comment by lgatto** [comment]
Do the results include the parameters?

**Comment by lmsimp** [comment]
These have been added the `E14TG2a` dataset in `experimentData`. Need to check other datasets

**Comment by lgatto** [comment]
Can this issue be closed?
