### ISSUE TITLE
Data from Beltran et al. 2016

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRolocdata#17]
_A Portrait of the Human Organelle Proteome In Space and Time during Cytomegalovirus Infection_ Pierre M. Jean Beltran, Rommel A. Mathias and Ileana M. Cristea. http://dx.doi.org/10.1016/j.cels.2016.08.012

**Comment by ococrook** [comment]
This dataset is a time course with 5 times. Each time has paired mock and infected - do we want this has 10 seperate files MSnsets?

**Comment by lgatto** [comment]
Yes, I suggest we do include all the data, as 10 different `MSnSet` objects. You can generate the `MSnSet`s yourself, or give me the data (cvs, I presume) and I will create them. The procedure to data in `pRolocdata` is:
1. the original data (often from supplementary material) is added to `inst/extdata`, say `newdata_1.csv`, `newdata_2.csv`, ... (the name should be the same as the original file(s)), and the files and provenance is documented in `inst/extdata/README`. If the data files are really too big, then we might decide not to added them, but they should still be documented in the `README` file and the script (see point 2) should still assume they are there.
2. A script, typically called `newdata.R` or `Beltran2016.R`, is added to `inst/scripts/`. That script reads the files above and saves the corresponding (compressed) `MSnSet` objects directly in `data`. 
3. Write a `man/Beltran2016.Rd` documentation file.
4. Build and check the package and, if successful, send a pull request.

**Comment by lgatto** [comment]
Done in commit 87dc7ad693513c58cc08c58fc5a764390b02fbc7.

**But note**: These data are corrupted: some 31 values are formatted as number and dates (see below and [here](https://twitter.com/lgatt0/status/974756030793043969) for details). An email has been sent to the authors. In the meantime, these values are set to `NA`.

![2018-03-17-000418_897x213_scrot](https://user-images.githubusercontent.com/384198/37550509-7f2ab016-2986-11e8-8a8a-2d4ef0ed6acf.png)
