### ISSUE TITLE
Rename andy2011

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRolocdata#18]
to `HEK293T2011`.

**Comment by lgatto** [comment]
@lmsimp - Lisa, is there any script that generates the GO and HPA data for `andy2011`? I can't find anything in the package itself.

Also, there's currently `andy2011goCC.rda` and `andy2011goCC.RData`. Is this an error? (I am actually surprised this doesn't show up during check)

**Comment by lmsimp** [comment]
>@lmsimp - Lisa, is there any script that generates the GO and HPA data for andy2011? I can't find anything in the package itself.

No there isn't. 

>Also, there's currently andy2011goCC.rda and andy2011goCC.RData. Is this an error? (I am actually surprised this doesn't show up during check)

Yes, this is an error. They are both he same object as far as I can tell.

**Comment by lgatto** [comment]
> Yes, this is an error. They are both he same object as far as I can tell.

Could you investigate, because the file size doesn't match.
```
-rw-rw-r-- 1 lg390 lg390  45K Jul 17  2015 andy2011goCC.rda
-rw-rw-r-- 1 lg390 lg390  89K Jul 17  2015 andy2011goCC.RData
```
I haven't looked at the data though.

**Comment by lgatto** [comment]
I'm looking into this. `RData` seems to be the correct one.

**Comment by lmsimp** [comment]
You beat me to it! Agreed 👍🏻
