### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by lgatto** [lgatto/pRolocdata#19]
- [ ] Christopher Gerner
- [ ] Joint MCP with Myriam Ferro's on sub-tylakoids localisation (3 biol reps, 2 techn reps). They should have MSnSets ready.
- [x] Christian Ahres bacteria (dynamic) data (see `stekhoven2014`)
- [ ] L Foster's last paper: [Development of a computational framework for
  the analysis of protein correlation profiling and spatial
  proteomics experiments](http://www.sciencedirect.com/science/article/pii/S1874391914005247). All the scripts described, together with representative test datasets, are available from our website (http://www.chibi.ubc.ca/faculty/foster/software/).
- [x]  Katerina's U-2 OS see #20 
- [ ] Data from Arrivault *et al.* 2014 (Schulze lab) [PMID link](https://www.ncbi.nlm.nih.gov/pubmed/24866124).
- [ ] Data from Jadot et al 2016 #22

**Comment by lmsimp** [comment]
Myriam's should already be in `pRolocdata` is this not the `at_chloro` dataset?

**Comment by lgatto** [comment]
> Myriam's should already be in `pRolocdata` is this not the `at_chloro` dataset?

I am thinking of 
> Tomizioli M, et al. Deciphering thylakoid sub-compartments using a mass spectrometry-based approach, [Mol Cell Proteomics. 2014 May 28](https://www.ncbi.nlm.nih.gov/pubmed/24872594)
