### ISSUE TITLE
Katerina's human U-2 OS

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#20]
- Add Katerina's two replicates to `pRolocdata`.
- There is a third replicate on the way, but at least add the other two for now.
- No immediate rush but let KSL know what this is done as she wants to look at them.

**Comment by lgatto** [comment]
Do we have official clearance to add this *unpublished* data?

**Comment by lmsimp** [comment]
Yes

**Comment by lmsimp** [comment]
I will triple check though

**Comment by lgatto** [comment]
@lmsimp - any news about this data?

**Comment by lgatto** [comment]
This data is not available in `pRolocdata` version `1.13.2` as `hyperLOPITU2OS2017` and `hyperLOPITU2OS2017b` (37 fractions).
