### ISSUE TITLE
Add data from Mann et al 2018 

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#36]
Add data from Mann's [recent publication](https://doi.org/10.1016/j.devcel.2018.09.017) on PCP phosphoproteomics.

Data is in table S3. A quick look at a the protein level data -

![mann-pca](https://user-images.githubusercontent.com/1698853/47778475-e78e7400-dcee-11e8-82db-d764564411a4.png)
![mann-tsne](https://user-images.githubusercontent.com/1698853/47778481-ebba9180-dcee-11e8-8d58-3136c7b66c66.png)

NB: Shape of PCA attributed to lots of missing values and heavy use of zero imputation.

**Comment by lgatto** [comment]
The data and files should be called `krahmer2018`, to fit with what has been done so far.

**Comment by ococrook** [comment]
I'll try and add the data this week

**Comment by lgatto** [comment]
Thanks @ococrook

**Comment by ococrook** [comment]
pull request made for half the data (no phospho just yet) ... I could not find a marker list @lmsimp  did you come across one?

**Comment by lmsimp** [comment]
@ococrook There must one as the markers I used above are not ours (we don't have a sub-compartment called LD). I'll have a quick look and see where I found this.

**Comment by lmsimp** [comment]
Sorry @ococrook I'm not at work so can't access Cell. I can check Monday?

**Comment by ococrook** [comment]
Looking at the Phosphodata from this paper, peptide data is provided with quite a lot of information - such as which residue was phosphoralated, multiplicity, protein group. I'm wondering what data we would provide - should we provide a dataset with peptide identifier as rownames or protein group as rownames. In the latter case, how do we collapse the quantitative data? How do we handle that different residues might be phosphoralated?

**Comment by lmsimp** [comment]
Is there quantitation data at both the peptide and the protein level?

**Comment by lmsimp** [comment]
Or are they the same in this case? And what you have is peptide and protein meta data? Can you provide a link to the .csv file so we can take a look?

**Comment by lgatto** [comment]
Phospho-date is better analysed at the peptide level anyway, so I would provide that. The aggregation into proteins will be a matter of choice depending on application. As for feature names, I would recommend peptide sequence, either passed through `make.unique` or by appending the master protein name.

**Comment by ococrook** [comment]
@lgatto I think we can close this one?
