### ISSUE TITLE
add Courtland et al data

### ISSUE THREAD

**Issue by ococrook** [lgatto/pRolocdata#57]
dynamic LOPIT paper from mouse brains:

https://www.biorxiv.org/content/10.1101/2020.08.06.239517v1

**Comment by ococrook** [comment]
data and scripts are here: https://github.com/twesleyb/SwipProteomics

**Comment by ococrook** [comment]
@lgatto  see last pull request - accidently pushed to master instead of my branch

**Comment by lgatto** [comment]
No worries.

**Comment by ococrook** [comment]
I think this issue can be closed ? @lgatto
