### ISSUE TITLE
add Claire's THP LOPIT data

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#61]
Add peptide and protein level triplicates for both the LOPIT and timecouse

**Comment by lmsimp** [comment]
I have lots of data to contribute these are the following - 

LOPIT data (as will be per the manuscripts supporting info)
- 3 replicates per condition (0 hour and 12 hour THP stimulation) = 6 protein level datasets 
(where each replicate contains 2 sets) 
- 2 combined protein level datasets of the above (one per condition)

Timecouse
- 3 reps of LPS stimulation (containing 6 time points 0, 2, 4, 6, 12, 24 hours)

All the above are straightforward to add. 

PSM data - 
I wish to add the PSM level data. This is 12 LOPIT datasets. 6 per condition (3 sets per condition). Would it be most useful to add just as it is and let those who are interested do their own filtering/imputation/combining etc? @lgatto @ococrook

**Comment by lgatto** [comment]
PSM is definitely great, but I would also suggest to either (1) provide the protein-level data, as was used in the paper, and on which the conclusions are based and/or (2) the exact code to generate the protein-level data.

**Comment by lmsimp** [comment]
Sorry if above comment wasn’t clear. Yes, have already added all protein level data in the branch (not yet pushed) but my question is whether I should provide PSM (1) as it is was given to me unprocessed or (2) processed/imputation etc. I thought (1) is best as this is then available for testing algorithms etc?

**Comment by lgatto** [comment]
Sure, please also add the PTM data.

**Comment by ococrook** [comment]
I assume @lgatto means PSM data unless I missed something. I theink the "raw" PSM data would be best with a script in inst on how it was processed. What do you think @lmsimp ?

**Comment by lmsimp** [comment]
Hey @ococrook yes I have assumed @lgatto meant PSM and that is what will be added when I've fixed [this](https://github.com/lgatto/pRolocdata/pull/62#pullrequestreview-568145911)

**Comment by lmsimp** [comment]
merged in #62
