### ISSUE TITLE
Update datasets used in Breckels et al 2015

### ISSUE THREAD

**Issue by lmsimp** [lgatto/pRolocdata#7]
- [x] TL parameters for SVM and k-NN for each dataset
- [x] TL results for E14 data (no results for other datasets as we did not classify the unknowns)
- [x] Add auxiliary data for YLoc 
- [x] Add auxiliary data for GO
- [x] Add auxiliary data for HPA

**Comment by lgatto** [comment]
See also issue #6

**Comment by lgatto** [comment]
@lmsimp should this not be closed?
